In [1]:
import numpy as np

1. Write a function, foo_1, that takes a NumPy array arr and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’


In [2]:
def foo_1(arr, target):
    if target not in arr:
        return 'no item found'

    differences = np.abs(arr-target)

    closest = np.where(differences == np.min(differences))[0]

    return closest

arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 7
print(foo_1(arr, target))


[2 3 4 5 6 8]


In [3]:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])
target = 11
print(foo_1(arr, target))


no item found


2. Write a user defined function foo_2 that takes a 1 or 2 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis.


In [4]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis)

    return non_zero

arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

result = foo_2(arr, axis=1)
print(result)

[4 1 2]


In [5]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis)

    return non_zero

arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

result = foo_2(arr, axis=0)
print(result)

[2 2 2 1]


In [6]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis=axis)

    return non_zero

arr1 = np.array([[[1, 2, 3, 4],
                  [0, 5, 0, 0],
                  [2, 0, 1, 0]],

                 [[2, 0, 1, 0],
                  [0, 5, 0, 0],
                  [1, 2, 3, 4]]])

result = foo_2(arr1, axis=0)
print(result)

[[2 1 2 1]
 [0 2 0 0]
 [2 1 2 1]]


In [7]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis=axis)

    return non_zero

arr1 = np.array([[[1, 2, 3, 4],
                  [0, 5, 0, 0],
                  [2, 0, 1, 0]],

                 [[2, 0, 1, 0],
                  [0, 5, 0, 0],
                  [1, 2, 3, 4]]])

result = foo_2(arr1, axis=1)
print(result)


[[2 2 2 1]
 [2 2 2 1]]


In [8]:
def foo_2(arr, axis):
    non_zero = np.count_nonzero(arr, axis=axis)

    return non_zero

arr1 = np.array([[[1, 2, 3, 4],
                  [0, 5, 0, 0],
                  [2, 0, 1, 0]],

                 [[2, 0, 1, 0],
                  [0, 5, 0, 0],
                  [1, 2, 3, 4]]])

result = foo_2(arr1, axis=2)
print(result)


[[4 1 2]
 [2 1 4]]


3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.


In [10]:
student_scores = np.random.randint(60,100,(4,3))
print(student_scores)

above_90_mask = np.any(student_scores > 90, axis=1)
resulting_array = student_scores[above_90_mask]

print('Resulting Array: ')
print(resulting_array)

[[94 76 60]
 [66 60 82]
 [65 88 81]
 [80 65 98]]
Resulting Array: 
[[94 76 60]
 [80 65 98]]


3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.


In [11]:
sales_data = np.random.randint(90,350,(4,4))
print(sales_data)

mean_values = np.mean(sales_data, axis=1)

median_values = np.median(sales_data, axis=1)

standard_deviation_values = np.std(sales_data, axis=1)

best_month_sales = np.argmax(sales_data, axis=1)

for i in range(len(mean_values)):
    print(f"Product {i+1}:")
    print(f"Mean: {mean_values[i]}")
    print(f"Median: {median_values[i]}")
    print(f"Standard Deviation: {standard_deviation_values[i]}")
    print(f"Month with the highest sales: Month {best_month_sales[i] + 1}")
    print()


[[334 315 337 141]
 [305 152 198 274]
 [218 102 202 245]
 [168 115 325 211]]
Product 1:
Mean: 281.75
Median: 324.5
Standard Deviation: 81.69876070051491
Month with the highest sales: Month 3

Product 2:
Mean: 232.25
Median: 236.0
Standard Deviation: 60.51601027827264
Month with the highest sales: Month 1

Product 3:
Mean: 191.75
Median: 210.0
Standard Deviation: 54.04801106423806
Month with the highest sales: Month 4

Product 4:
Mean: 204.75
Median: 189.5
Standard Deviation: 77.30580508603478
Month with the highest sales: Month 3



3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.


In [13]:
random_array = np.random.randint(1, 101, size=1000)
print(random_array)

unique_values, counts = np.unique(random_array, return_counts=1)

sorted_indices = np.argsort(counts)[::-1]

top_values = unique_values[sorted_indices[:10]]
top_counts = counts[sorted_indices[:10]]

print("Top 10 most frequently occurring values:")
for value, count in zip(top_values, top_counts):
    print(f"{value}: {count} occurrences")

[ 75   3  98  56  71  21  50  94  52  71  53  31  27  56  25  12  78  11
  69 100  43  23  89   6  42  83  71  96  40  97  90  22  87  31   9  90
   3  43  30   3  38  61  93   7  41  58  62   5   5  99  25  14   5  11
  81   1  99   8  34  72  87  90  18  44  85  49   5  82  61   9  35  25
  57  79  52  35  60  81  93   1  53  50  43  94  49  15   5  33  70  88
  72  67  11   5  68  70  27  14  41  16  50  56  45  89  80  68  59   9
   6  90  25  48  38   4  23  57 100  49  93  49  60  20  99  54  45  11
   9  44  51  59  29  20  94  58  42   7  82  63  64  49  59  40  86   6
  62  56  65  45  58  52  89  88  14   3  85  86  85  56  58  64  67  30
  13  42  35  40  72  99   9  12  99  31  21  92  78  28   4  88  37  89
  29  18  11  97  81  94  90  13  36  97  68  19  84  98  58  28  34  54
  80  42  59  82  93  76  33  41  21  96   1  89  65  36   3  31  15  70
  10  15  18  14  41   6  48  59  84  93  38  94  25 100   8  16  78  97
  21  55  33  19  51   8  83  66  68  81   8  73  7